name: macos

on:
  - push

jobs:
  perl:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Perl
        run: brew install perl
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          curl -L https://cpanmin.us | perl - -nq --installdeps .
          curl -L https://cpanmin.us | perl - -n TAP::Formatter::GitHubActions
      - name: Run Tests
        run: prove --merge --formatter TAP::Formatter::GitHubActions -l t
