name: perltidy

on:
  - push

jobs:
  perltidy:
    runs-on: ubuntu-latest
    container:
      image: perl:latest
    steps:
      - uses: actions/checkout@v3
      - name: Fix git permissions
        # work around https://github.com/actions/checkout/issues/766
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: cpanm -n Perl::Tidy
      - name: perltidy --version
        run: perltidy --version
      - name: Run perltidy
        shell: bash
        run: |
          shopt -s extglob globstar nullglob
          perltidy --pro=.../.perltidyrc -b -bext='/' **/*.p[lm] **/*.t && git diff --exit-code
