name: perlcritic

on: 
  - push

jobs:
  perlcritic:
    runs-on: ubuntu-latest
    container:
      image: perl:latest
    steps:
      - uses: actions/checkout@v3
      - name: Fix git permissions
        # work around https://github.com/actions/checkout/issues/766
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: cpanm -n Perl::Critic Perl::Critic::Policy::Documentation::RequirePodLinksIncludeText Perl::Critic::Policy::Miscellanea::RequireRcsKeywords
      - name: perlcritic --version
        run: perlcritic --version
      - name: Run perlcritic
        shell: bash
        run: perlcritic lib
